### PR TITLE
Changed the "level" column in "log" table to be integer again

### PR DESCRIPTION
**Pull request by Dzhuneyt**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii-core/issues/132

### CODE REVIEW

**Comment by samdark** [comment]
How about making it a single migration? We can do that since there were no package releases yet.

**Comment by Dzhuneyt** [comment]
@samdark what about customers that upgrade from an older version of Yii? They will have the old migration already executed and the column type the wrong one.

**Comment by samdark** [comment]
There is no compatibility guarantee between Yii 2.0 and Yii 3.0. But if you think that two separate migrations are better, I'm fine with it.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by Dzhuneyt** [comment]
> There is no compatibility guarantee between Yii 2.0 and Yii 3.0. But if you think that two separate migrations are better, I'm fine with it.

I have bad experiencing changing old migrations' code for ANY reason in my day job. That's all :)

**Comment by Dzhuneyt** [comment]
@samdark just out of curiousity, now that a lot of functionalities have been moved outside of the yii-core project into their own dedicated projects - will they all have their own CHANGELOG file (I see this one doesn't for example).

**Comment by samdark** [comment]
Yes. After first release.

**Pull request merged**
