### PR TITLE
CHANGELOG and UPGRADE

### PR DESCRIPTION
**Pull request by FabrizioCaldarelli**

### CODE REVIEW

**Comment by rob006** [comment]
Both changelog and upgrade entries are unnecessary. Test are irrelevant from user perspective, so they're should not be mentioned in changelog. And `m180103_040100_log_change_level_to_int` was never released, so there is no point in mentioning it in upgrade guide.

**Comment by FabrizioCaldarelli** [comment]
Should I remove both?

**Comment by rob006** [comment]
I'm not sure that we need changelog and upgrade guide at this point - right now changes are so frequent and chaotic that it may be easier to write them after first (alpha?) release as a summary.

**Comment by samdark** [comment]
I think that it's easier to write changelog and updade as we go.

**Comment by FabrizioCaldarelli** [comment]
So I put empty files (I leave the header) ?

**Comment by samdark** [comment]
Yep.

**Comment by FabrizioCaldarelli** [comment]
Done

**Pull request merged**
