### PR TITLE
Fix/configure targets

### PR DESCRIPTION
**Pull request by pgaultier**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #1

### CODE REVIEW

**Comment by hiqsol** [comment]
No that's not what we want in the long term.
Log, cache, di, db are packages that we want to make independent of the yii-core and usable outside of yii.
Things you want from component need to be copied.

**Comment by pgaultier** [comment]
Ok, I understand but I didn’t thought it was a bad thing as `yii\base\Component` is already used in `src/Target`

**Comment by hiqsol** [comment]
That's how it goes at the moment.
Gradually forward, but no steps back :)
Anyway thank you.

**Comment by pgaultier** [comment]
@hiqsol @samdark 
Just one question, `yiisoft/log` rely on 
 * `yiisoft/yii-core` for `yii\base\Component` and exceptions to init `Logger`
 * `yiisoft/di` to create targets
 * ...
I understand this is because we inherit a lot of stuff from yii2 but if we reintegrate everything which is needed in `yiisoft/log` don't you think we will duplicate a lot of code ? 

Have you some ideas how we should do this ?

**Comment by hiqsol** [comment]
I need to take a closer look.
Lots of things has been changed and fixed after changes. And logger will be fixed too.
I hope everything could be fixed without lots of duplication.

**Comment by hiqsol** [comment]
Please see https://github.com/yiisoft/log/commit/7764e39995bd6e372fbfc0d88d1a6d6bb0d7cea6

This is example what I consider to be preferred over getter/setter/magic variables.
Simple constructor. It is well supported in DI now.

**Pull request closed without merging**
